config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#index", as: "root"
  get "/sitemap", to: "sitemap#index"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"

  get "/print", to: "print#index"
  resources :print

  get "/film", to: "film#index"
  get "/film/last-night-i-had-this-dream", to: "film#lastNightIHadThisDream"
  get "/film/limbo", to: "film#limbo"
  get "/film/angela", to: "film#angela"
  get "/film/vem-plus", to: "film#vemPlus"
  get "/film/zeina", to: "film#zeina"
  get "/film/where-do-i-even-start", to: "film#whereDoIEvenStart"

  get "/commercial", to: "commercial#index"
  get "/commercial/henriette-von-gruenberg", to: "commercial#henrietteVonGruenberg"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commercial_controller.rb
class CommercialController < ApplicationController
    def index
    end

    def henrietteVonGruenberg
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/fashion_controller.rb
class FashionController < ApplicationController
    def index
    end

    def henrietteVonGruenberg
    end
end

app/controllers/film_controller.rb
class FilmController < ApplicationController
    def index
    end

    def lastNightIHadThisDream
    end

    def limbo
    end

    def angela
    end

    def vemPlus
    end

    def zeina
    end

    def whereDoIEvenStart
    end
end

app/controllers/print_controller.rb
class PrintController < ApplicationController
    def index
    end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
    layout "sitemap"

    def index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_class?(test_path)
        return 'active' if request.path == test_path
        ''
      end
end

app/helpers/commercial_helper.rb
module CommercialHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/film_helper.rb
module FilmHelper
end

app/helpers/print_helper.rb
module PrintHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<% content_for :head do %> <title>About - Ari Salazar </title>  <% end %>

<div class="content about">
    <div class="about-container about1"><%= image_tag("about/about1.jpg", :class => "img", alt: "Ari Salazar portrait")%></div>
    <p>Ari Salazar is an artist and filmmaker based in London. Her practice explores themes of identity, belonging and home through performance art, memory and oral testimony.</p>
    <p>Along with her work for the UN, EU and the War Studies Institute, she has worked on various short films, fashion commercials and documentaries.</p>
    <p>Request CV for more info.</p>
    <div class="about-container about2"><%= image_tag("about/about2.png", :class => "img", alt: "Ari Salazar photo")%></div>
    <div class="about-container about3"><%= image_tag("about/about3.png", :class => "img", alt: "Ari Salazar photo")%></div>
</div>

app/views/commercial/henrietteVonGruenberg.html.erb
<% content_for :head do %> <title>Henriette Von Gruenberg | Commercial - Ari Salazar </title>  <% end %>

<div class="content project">
    
    <div class="project-container"><%= image_tag("commercial/HENRIETTE_INDIVIDUAL.jpg", :class => "img", alt: "Ari Salazar commercial film Henriette Von Gruenberg")%></div>

        <div class="text">
        <p class="thick">Henriette Von Gruenberg</p>
        <p>Director Tara Aghdashloo seamlessly captures the soft tones and textures of Henriette Von Gruenberg's luxury sustainable fashion brand.<p>

        <div class="credits">
                <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Year</li>
                    <li>Model/Designer</li>
                    <li>Director of Photography</li>
                    <li>Editors</li>
                    </br>
                    <li>Production</li>
                    <li>1st Assistant Camera</li>
                    <li>1st Assistant Camera</li>
                    <li>Hair and Make-up</li>
                    <li>Style Assistant</li>
                    <li>Set Assist</li>
                    <li>Music</li>
                    <li>Rental Company</li>
                </ul>
                <ul class="values">
                    <li>Tara Aghdashloo</li>
                    <li>2019</li>
                    <li>Henriette Von Grunberg</li>
                    <li>Claudio Napoli</li>
                    <li>James Gunn</li>
                    <li>Tara Aghdashloo</li>
                    <li>t.a studios</li>
                    <li>Valeria Lattanzi</li>
                    <li>Ari Salazar</li>
                    <li>Alexandra Staggl</li>
                    <li>Sasha Zlatkina</li>
                    <li>Isabella Leitz</li>
                    <li>Sassy Moon by Hairband</li>
                    <li>VMI Ltd.</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/commercial/index.html.erb
<% content_for :head do %> <title>Ari Salazar | Commercial</title>  <% end %>

<div class="content index">
    <a class="index-container fade" href="commercial/henriette-von-gruenberg" data-text="Henriette Von Gruenberg / Fashion">
    <%= image_tag("commercial/HENRIETTE.jpg", :class => "img", alt: "Ari Salazar commercial film Henriette Von Gruenberg")%>
    </a>
</div>

app/views/contact/index.html.erb
<% content_for :head do %> <title>Ari Salazar | Contact</title>  <% end %>

<div class="content contact">
    <p>For projects, commissions, collaborations, or to buy prints, please email me at arisalazarfilm@gmail.com</p>
</div>

app/views/film/angela.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Angela</title>  <% end %>

<div class="content project">
    
    <div class="project-container"><img></img></div>

    <div class="text">
        <p class="thick">Angela</p>
        <p>Angela Camargo is Panama’s oldest, and most celebrated restorationist. We accompany her on her daily walk through Casco Viejo, listening to her life story as she feeds the old city center’s cats. What has kept her working all these years?<p>

            <div class="credits">
            <div class="row">
                <ul class="keys">
                    <li>Filmmaker</li>
                    <li>Country</li>
                    <li>Year</li>
                    <li>Format</li>
                    <li>Length</li>
                    <li>Language</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Panama, UK</li>
                    <li>2020</li>
                    <li>Digital</li>
                    <li>7:00</li>
                    <li>English</li>
                </ul>
            </div>
            <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Producer</li>
                    <li>Cinematographer</li>
                    <li>Editor</li>
                    <li>Sound Designer</li>
                    <li>Cast</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Gunay Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Angela Camargo</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/film/index.html.erb
<% content_for :head do %> <title>Ari Salazar | Film</title>  <% end %>

<div class="content index">

    <a class="index-container fade" href="film/angela" data-text="Angela / Documentary">
        <%= image_tag("film/index/ANGELA.jpg", :class => "img", alt: "Ari Salazar documentary film Angela")%>
    </a>

    <a class="index-container fade" href="film/zeina" data-text="Zeina / Documentary">
        <%= image_tag("film/index/ZEINA.jpg", :class => "img", alt: "Ari Salazar documentary film Zeina")%>
    </a>
    
    <a class="index-container fade" href="film/where-do-i-even-start" data-text="Where Do I Event Start / Documentary">
        <%= image_tag("film/index/WHEREDOIEVENSTART.jpg", :class => "img", alt: "Ari Salazar documentary film Where Do I Even Start")%>
    </a>

    <a class="index-container fade" href="film/last-night-i-had-this-dream" data-text="Last Night I Had this Dream / Experimental">
        <%= image_tag("film/index/LASTNIGHTIHADTHISDREAM.jpg", :class => "img", alt: "Ari Salazar experimental film Last Night I Had this Dream")%>
    </a>

    <a class="index-container fade" href="film/limbo" data-text="Limbo / Experimental">
        <%= image_tag("film/index/LIMBO.jpg", :class => "img", alt: "Ari Salazar experimenta film Limbo")%>
    </a>

    <a class="index-container fade" href="film/vem-plus" data-text="VEM+ / Documentary">
        <%= image_tag("film/index/VEM.jpg", :class => "img", alt: "Ari Salazar experimenta documentary film Vem+")%>
    </a>
</div>

app/views/film/lastNightIHadThisDream.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Last Night I Had this Dream</title>  <% end %>

<div class="content project">
    
    <div class="project-container">
        <%= image_tag("film/individual/LASTNIGHTIHADADREAM_INDVIDUAL.jpg", :class => "img", alt: "Ari Salazar experimental film Last Night I Had this dream")%>
    </div>
    
    <div class="text">
        <p class="thick">Last Night I Had this Dream</p>
        <p>A poetic meditation on the absurd experience of isolation during COVID-19.<p>

        <div class="credits">
            <div class="row">
                <ul class="keys">
                    <li>Filmmaker</li>
                    <li>Country</li>
                    <li>Year</li>
                    <li>Format</li>
                    <li>Length</li>
                    <li>Language</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Austria</li>
                    <li>2020</li>
                    <li>Digital</li>
                    <li>2:00</li>
                    <li>English</li>
                </ul>
            </div>
            <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Cinematographer</li>
                    <li>Editor</li>
                    <li>Sound Designer</li>
                    <li>Cast</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Jascha Dor</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/film/limbo.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Limbo</title>  <% end %>

<div class="content project">
    
    <div class="project-container">
        <%= image_tag("film/individual/LIMBO_INDVIIDUAL.jpg", :class => "img", alt: "Ari Salazar experimental film Limbo")%>
    </div>
    
    <div class="text">
        <p class="thick">Limbo</p>
        <p>A surrealist short on a young high schooler’s late night subway rides in New York City.<p>

        <div class="credits">
            <div class="row">
                <ul class="keys">
                    <li>Filmmaker</li>
                    <li>Country</li>
                    <li>Year</li>
                    <li>Format</li>
                    <li>Length</li>
                    <li>Language</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>USA</li>
                    <li>2015</li>
                    <li>Digital</li>
                    <li>2:00</li>
                    <li>English</li>
                </ul>
            </div>
            <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Cinematographer</li>
                    <li>Editor</li>
                    <li>Sound</li>
                    <li>Cast</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Mango Fury</li>
                    <li>Joel Gorlick</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/film/vemPlus.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Vem+</title>  <% end %>

<div class="content project">
    
    <div class="project-container">
        <%= image_tag("film/individual/VEMINDIVIDUAL.jpg", :class => "img", alt: "Ari Salazar documentary film vem+")%>
    </div>
    
    <div class="text">
        <p class="thick">Vem+</p>
        <div class="synopsis">
            The VEM+ network is an interdisciplinary research project based within the Faculty of Social Sciences & Public Policy at King's College London. The project aims to merge visual, embodied and arts-based methodologies with the social sciences. The documentary follows four pairs of VEM+ researchers and artists' collaborative process during a weeklong art residency.  During this time, we get to know their complex treatment of issues of migrant rights, gender justice, the rise in nationalism and post-war reconciliation processes.
            </br></br>
            Find out more about the project <a href="https://www.kcl.ac.uk/research/visual-embodied-methodologies">here</a>.
        </div>

        <div class="credits">
            <div class="row">

                <ul class="keys row-one">
                    <li>Filmmaker</li>
                    <li>Country</li>
                    <li>Year</li>
                    <li>Format</li>
                    <li>Length</li>
                    <li>Language</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>UK</li>
                    <li>2019</li>
                    <li>Digital</li>
                    <li>15:00</li>
                    <li>English</li>
                </ul>
            </div>
            
            <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Producer</li>
                    <li>Cinematographer</li>
                    <li>Editor</li>
                    <li>Sound Designer</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                </ul>
            </div>

            <div class="row row-three">
                <ul class="keys">
                    <li>Cast</li>
                </ul>
                <ul class="values">
                    <li>Prof Cathy McIlwaine</li>
                    <li>Gaël Le Corne</li>
                    <li>Dr Negar Elodie Behzadi</li>
                    <li>Dr Jelke Boesten</li>
                    <li>Dr Henry Redwood</li>
                    <li>Vladimir Miladinović</li>
                    <li>Dr Pablo De Orellana</li>
                    <li>Mariah Whelan</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/film/whereDoIEvenStart.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Where Do I Even Start</title>  <% end %>

<div class="content project">
    
    <div class="project-container">
        <%= image_tag("film/individual/IDA_INDVIDUAL.jpg", :class => "img", alt: "Ari Salazar film Where do I even start")%>
    </div>

        <div class="text">
            <p class="thick">Where Do I Even Start </p>
            <p>An experimental short film that traces the passage of a relationship from its beginnings to its breakdown.</p>

            <div class="credits">
                <div class="row">
                    <ul class="keys">
                        <li>Filmmaker</li>
                        <li>Country</li>
                        <li>Year</li>
                        <li>Medium</li>
                        <li>Length</li>
                        <li>Language</li>
                    </ul>
                    <ul class="values">
                        <li>Ari Salazar</li>
                        <li>UK</li>
                        <li>2020</li>
                        <li>Digital</li>
                        <li>5:00</li>
                        <li>English</li>
                    </ul>
                </div>
                <div class="row">
                    <ul class="keys">
                        <li>Director</li>
                        <li>Cinematographer</li>
                        <li>Editor</li>
                        <li>Sound</li>
                        <li>Cast</li>
                    </ul>
                    <ul class="values">
                        <li>Ari Salazar</li>
                        <li>Ari Salazar</li>
                        <li>Ari Salazar</li>
                        <li>Ari Salazar</li>
                        <li>Ida Vaansgard Christensen</li>
                    </ul>
                </div>
            </div>
        </div>
</div>

app/views/film/zeina.html.erb
<% content_for :head do %> <title>Ari Salazar | Film | Zeina</title>  <% end %>

<div class="content project">
    
    <div class="project-container"><%= image_tag("film/individual/ZEINA_INDIVIDUAL.JPG", :class => "img", alt: "Ari Salazar documentary film Zeina")%></div>
    
    <div class="text">
        <p class="thick">Zeina</p>
        <p class="synopsis">A short observational documentary that traces a young Egyptian woman's intimate conversations on everyday racism and discrimination on a night out in London.</p>

        <div class="credits">
            <div class="row">

                <ul class="keys">
                    <li>Filmmaker</li>
                    <li>Country</li>
                    <li>Year</li>
                    <li>Format</li>
                    <li>Length</li>
                    <li>Language</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>UK</li>
                    <li>2020</li>
                    <li>Digital</li>
                    <li>7:00</li>
                    <li>English, Arabic</li>
                </ul>
            </div>
                <div class="row">
                <ul class="keys">
                    <li>Director</li>
                    <li>Cinematographer</li>
                    <li>Editor</li>
                    <li>Sound</li>
                    <br> 
                    <li>Cast</li>
                </ul>
                <ul class="values">
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Ari Salazar</li>
                    <li>Semeli Safou</li>
                    <li>Ari Salazar</li>
                    <li>Zeina Dowidar</li>
                    <li>Nada Aboul Kheir</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= yield :head %>
    <meta charset="UTF-8">
    <meta name="title" content="Ari Salazar | Artist and Film Maker">
    <meta name="description" content="Ari Salazar is an artist and filmmaker based in London. She has worked on various short films, fashion commercials and documentaries.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="WRoKruPijlfnW4LpPRnxjQNxC4Jtf_qdbaySCxfzRRM" />  
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logos/enter.png') %>
  </head>
  <body>
    <div class="page">
      <header>
        <a id='title' href="https://www.arisalazar.com/film"><%= image_tag("logos/name-logo.png", width: '130px', :class => "title-logo") %></a>

        <nav>
          <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>

          <ul class="menu">
            <li><%= link_to 'film', film_path, :class => current_class?(film_path)  %></li>
            <li><%= link_to 'commercial', commercial_path, :class => current_class?(commercial_path)  %></li>
            <li><%= link_to 'print', print_path, :class => current_class?(print_path)  %></li>
            <li><%= link_to 'about', about_path, :class => current_class?(about_path)  %></li>
            <li><%= link_to 'contact', contact_path, :class => current_class?(contact_path)  %></li>
          </ul>
        </nav>
      </header>
      
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <p class="navbar-text float-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>

      <%= yield %>
      
      <footer class="footer">
        <div class="social-media">
          <a href="https://www.instagram.com/arisalzr/"><%= image_tag("logos/insta.png", width: '20px') %></a>
          <a href="https://www.facebook.com/ari.salazar"><%= image_tag("logos/facebook.png", width: '20px') %></a>
          <a href="https://vimeo.com/user33990006"><%= image_tag("logos/vimeo.png", width: '20px') %></a>
        </div>
      </footer>
    </div>
  </body>
  </html>

app/views/layouts/sitemap.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">


<url>
  <loc>https://www.arisalazar.com/</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/commercial</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/print</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/about</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/contact</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/angela</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/zeina</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/where-do-i-even-start</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/last-night-i-had-this-dream</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/limbo</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/film/vem-plus</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://www.arisalazar.com/commercial/henriette-von-gruenberg</loc>
  <lastmod>2020-06-13T15:09:50+00:00</lastmod>
  <priority>0.51</priority>
</url>


</urlset>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ari Salazar | Enter</title>
  <meta name="title" content="Ari Salazar | Artist and Film Maker">
  <meta name="description" content="Ari Salazar is an artist and filmmaker based in London. Her practice explores themes of identity, belonging and home through performance art, memory and oral testimony.">
  <meta name="google-site-verification" content="WRoKruPijlfnW4LpPRnxjQNxC4Jtf_qdbaySCxfzRRM" />  
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('logos/enter.png') %>
</head>
<body>
  <div class="landing-page">
    <ul id='landing-page'>
      <div class="landing-container"><li><%= image_tag("logos/landing-page-logo.png", :class => "lp-logo", alt: "Ari Salazar enter logo") %></li></div>
      <li><a class="enter" href="https://www.arisalazar.com/film"> enter </a></li>
    <ul>
  </div>
</body>

app/views/print/index.html.erb
<% content_for :head do %> <title>Ari Salazar | Print</title>  <% end %>

<div class="content">
    <div class="prints">       
        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print2.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></img></div>
            <div class="print-text">Antigua, Watercolor on Paper (15x18)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print3.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Portrait of a Papaya, Watercolor on Paper (20 x 30)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print4.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Awake, Asleep, Watercolor on Paper (25x35)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print5.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Blue, Pencil on Parchment (15x15)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print6.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Amor mio, Watercolor on Paper (18x22)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print7.jpg", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Untitled, Oil Pastel and Pen on Paper (20x30)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print8.JPG", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Asleep, Dreaming, Watercolor on Paper (30 x 20)</div>
        </div>

        <div class="row">
            <div class="print-container"><%= image_tag("prints/Print1.png", width: '300px', :class => "img", alt: "Ari Salazar print") %></div>
            <div class="print-text">Lady in Green, Acrylic on Paper (20x15)</div>
        </div>

    </div>
</div>